title: shopify.github.com
markdown: kramdown
url: https://shopify.github.io
baseurl: /
exclude: [
  'Gemfile',
  'Gemfile.lock'
]
defaults:
  - scope:
      path: ""
    values:
      toc: true
plugins:
  - jekyll-redirect-from
